### ISSUE TITLE
Not an actaul issue, just a lengthy thankyou/apology 

### ISSUE THREAD

**Issue by Einhart** [ma-al/ma-al.github.io#1]
Hey Mahathir, you may not remember me but i was the guy asking for help with a particular error regarding a Jumping Race Drone Nodejs issue I tried  to email you but it kept telling me the your ibm email was inactive. So i copy pasted my intended email below :-) I hope you are well and thanks again.

-------------------------------------------------------------------------------------------------------------------------------------

Mahathir First of all i want to apologise for this unacceptably late reply.
I have just finished the project and it has been a grueling sequence of sleepless nights getting it to work

But indeed it does work and it was in large part thanks to the modifications to sumo.js (if i remember correctly) that you made

I have made a video to show the different applications of the drones for the project
https://www.youtube.com/watch?v=YRTdp6EAi1E

the source code is not yet compiled and is a mess, but i hope to have it up on github sometime this weekend.
Thank you so much again and sorry for being MIA so long.

Best regards,
Sean

**Comment by ma-al** [comment]
I don't know how I've only _just_ seen this. Sorry! 🤦‍♂️ 

Yes, I've moved on from IBM Research and am now at Seeing Machines. Find me on [LinkedIn](https://au.linkedin.com/in/mahalm).

No worries mate. Glad to know you found my code useful.

The video was amazing. It must have been some effort to get the drone to recognise, localise and move to the colours... especially on a really crappy 480p camera. Well done!

Thanks for absolutely making my day 😄 Keep on coding. Take care.
